printWidth: 100
semi: true
singleQuote: false
quoteProps: "as-needed"
jsxSingleQuote: false
trailingComma: "none"
bracketSpacing: true
bracketSameLine: true
arrowParens: "always"
endOfLine: "auto"
singleAttributePerLine: true
